#!/usr/bin/env bash
#PBS -N %JOBNAME%
#PBS -A %ACCOUNT%
#PBS -q %PARTITION%
#PBS -l job_priority=%QOS%
#PBS -l select=%N_NODE%:ncpus=%ppn%:mpiprocs=%ppn%:mem=%MEMORY%
#PBS -l walltime=%WALLTIME%
#PBS -j oe
#PBS -o %LOGFILE%
#PBS -V

export HDF5_USE_FILE_LOCKING=FALSE
ulimit -s unlimited || true
ulimit -v unlimited || true

export VALIDATE_PARAMETERS=1

